### ISSUE TITLE
Infinite execution vulnerability

### ISSUE THREAD

**Issue by KAloraifi** [Turkiqsm/Book-Scanning-Problem#3]
Have a look at the infinite loop issue you mentioned.

_Originally posted by @KAloraifi in https://github.com/Turkiqsm/Book-Scanning-Problem/pull/2#issuecomment-592649177_

**Comment by hamadalaqeel** [comment]
Will do.

**Comment by KAloraifi** [comment]
![](https://media.giphy.com/media/m9eG1qVjvN56H0MXt8/source.gif)

**Comment by hamadalaqeel** [comment]
@KAloraifi  Did you solve it? I'm actually doing some research and testing it on samples right now.

**Comment by KAloraifi** [comment]
@hamadalaqeel No but I thought it was stale...
